#actuator端口
management:
  server:
    port: 8083
#修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
  endpoints:
    web:
  #开放所有页面节点  默认只开启了health、info两个节点
      exposure.:
        include: "*"
  #显示健康具体信息  默认不会显示详细信息
  endpoint:
    health:
      show-details: always